name: Build and deploy dotnet app
run-name: Build and deploy dotnet app

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'cms/**'

env:
    DOTNET_APP_LOCATION: cms
    DOTNET_APP_NAME: Explore.Cms

jobs:
  build:
    name: Build CMS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build CMS
        uses: ./.github/actions/build-dotnet-app
        with:
          app_location: ${{ env.DOTNET_APP_LOCATION }}

  deploy-dev:
    needs: [build]
    runs-on: ubuntu-latest
    environment: dev

    steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Deploy CMS
          uses: ./.github/actions/deploy-azure-function-app
          with:
              app_location: ${{ env.DOTNET_APP_LOCATION }}
              app_name: ${{ env.DOTNET_APP_NAME }}
              publish_profile: ${{ secrets.PROJECT_API_PUBLISH_PROFILE }}
